### ISSUE TITLE
Give new life to Hematite?

### ISSUE THREAD

**Issue by bvssvni** [PistonDevelopers/hematite#118]
I would like to see some new ideas of what to do with Hematite. Perhaps we should start moving stuff into a library "voxel"?

**Comment by abbottmg** [comment]
I actually arrived at this project specifically looking for a voxel rendering engine that I could use to play with a more mod-able minecraft. I'm a rust newb waiting for the stable beta to start learning the language, but I'd definitely like to get involved with the project as a training mechanism.

**Comment by fenhl** [comment]
As I have mentioned on IRC, I may try and start a “Minecraft server in Rust” project, which Hematite could use for the local singleplayer server once some progress has been made.

**Comment by bvssvni** [comment]
@fenhl You are welcome to start this project under PistonDevelopers, it would be a great match with Hematite!

**Comment by fenhl** [comment]
@bvssvni That would be great, although I'm still a Rust noob, and I would like to discuss some things with anyone interested in the project before actually creating a repo. Is there an IRC channel for this sort of thing?

**Comment by bvssvni** [comment]
@fenhl #rust-gamedev (there is a link in the sidebar on [r/rust_gamedev](http://www.reddit.com/r/rust_gamedev/))

**Comment by bvssvni** [comment]
Closing.
