### ISSUE TITLE
Remove prefix on `Nbt` and suffix on `List` variants

### ISSUE THREAD

**Issue by bvssvni** [PistonDevelopers/hematite#156]
- [x] `NbtString` => `String`
- [x] `NbtList` => `List`
- [x] `NbtCompound` => `Compound`

**Comment by toqueteos** [comment]
Still wanted? It's easy but requires to prepend `Nbt::` to avoid conflicts (`Nbt::String` vs `string::String`).

**Comment by toqueteos** [comment]
Also there's the List prefix on all of these:

- [ ] `ByteList` => `List::Byte`
- [ ] `ShortList` => `List::Short`
- [ ] `IntList` => `List::Int`
- [ ] `LongList` => `List::Long`
- [ ] `FloatList` => `List::Float`
- [ ] `DoubleList` => `List::Double`
- [ ] `ByteArrayList` => `List::ByteArray`
- [ ] `StringList` => `List::String`
- [ ] `ListList` => `List::List`
- [ ] `CompoundList` => `List::Compound`
- [ ] `IntArrayList` => `List::IntArray`

**Comment by eddyb** [comment]
I think we should prefer `Foo::Bar` to `Bar` or, worse, `FooBar`.
