### ISSUE TITLE
Build failing, Mac OS X Yosemite

### ISSUE THREAD

**Issue by galbacarys** [PistonDevelopers/hematite#165]
Not sure if this is a problem with Hematite, per se, but I'm getting the following error when I attempt to build Hematite using Cargo:

    Build failed, waiting for other jobs to finish...
    Only `-l` and `-L` flags are allowed in build script of `time v0.1.1 (http://github.com/rust-lang/time#288b362e)`: `-L /path/to/hematite/target/build/time-8bde1abd230448f0/out -l time_helpers:static`

Any ideas why this might be happening?

Current platform is Mac OS X Yosemite, newest version. SDL2 is installed, and Rust/Cargo were updated yesterday (12/11/14).

**Comment by mattico** [comment]
Related to https://github.com/rust-lang-deprecated/time/issues/42 and fixed by https://github.com/rust-lang/cargo/issues/1015.

I'm pretty certain this isn't an issue anymore, so I'm closing this.
