### ISSUE TITLE
Update to latest Minecraft

### ISSUE THREAD

**Issue by fenhl** [PistonDevelopers/hematite#176]
Readme says to use 1.8-pre2, which is no longer available in the launcher if you haven't already downloaded it.

**Comment by eddyb** [comment]
Was it never changed to say `1.8`? Maybe I never truly updated it (even though they should be identical for all intents and purposes).

**Comment by toqueteos** [comment]
It does work with 1.8.1, all tests I did were with that version and it does indeed work perfectly.

**Comment by fenhl** [comment]
So we could just update the version in the readme?
