### ISSUE TITLE
Build fail : no package 'render'

### ISSUE THREAD

**Issue by Yamakaky** [PistonDevelopers/hematite#182]
Hi
For me ([and travis](https://travis-ci.org/PistonDevelopers/hematite/builds/48905186)), the build fails with this message :

    no matching package named `render` found (required by `hematite`)
    location searched: https://github.com/gfx-rs/gfx-rs
    version required: *

**Comment by toqueteos** [comment]
Investigating...

**Comment by toqueteos** [comment]
Patch incoming..! gfx-rs did some changes:

- device is now gfx_device_gl.
- render is now inside gfx.

**Comment by Yamakaky** [comment]
Sorry for the poor bug report. I use ArchLinux with the latest nightly (just downloaded).
BTW, travis fails with the same error.

**Comment by Yamakaky** [comment]
Instead of hardcoding the git url, maybe you should use crates.io ?

**Comment by toqueteos** [comment]
This happens almost daily, nightlies change and something breaks.

The [FromStr](http://doc.rust-lang.org/std/str/trait.FromStr.html) trait got changed too so there's more changes to do in other places not just hematite.

**Comment by Yamakaky** [comment]
Be brave, a few weeks and it's in 1.0 !

**Comment by toqueteos** [comment]
gfx_voxel should be fixed in a moment, once that is patched will see if there are more problems on the way.

**Comment by Yamakaky** [comment]
You didn't answer my question : why don't you use crates.io ? If I'm right, you would not have to put the git repo url in your Cargo.toml, would you ?

**Comment by toqueteos** [comment]
@Yamakaky That's not my decision, I'm a recent contributor. It was already like that when I joined two weeks ago.

**MY OPINION:** Once we are stable enough, or just with Rust 1.0 we may go for crates.io versioning but right now it's just not worth the effort.

**Comment by Yamakaky** [comment]
Ok, thanks.

**Comment by bvssvni** [comment]
@Yamakaky The reason we use git urls is because we try to keep things updated, and when Travis CI fails we get a notice.

**Comment by Yamakaky** [comment]
ok.
