### ISSUE TITLE
Strange visual glitch on latest hematite build

### ISSUE THREAD

**Issue by toqueteos** [PistonDevelopers/hematite#187]
I didn't update to latest nighlies today (windows apparently is built every two days?) so I could still test hematite, something is very wrong.

```
$ rustc -V
rustc 1.0.0-nightly (ba2f13ef0 2015-02-04 20:03:55 +0000)
```

Here you have a video showing it: https://www.youtube.com/watch?v=Zjj2iv-wSEg

Any ideas what may be causing this? It seems like an issue with normals and culling.

**Comment by bvssvni** [comment]
I couldn't spot any repeating patterns. Perhaps it renders each chunk per frame?

**Comment by toqueteos** [comment]
You should be able to reproduce build by using a previous gfx-rs and nightlies. I'm sorry, windows here :/

**Comment by toqueteos** [comment]
Still there with `rustc 1.0.0-nightly (74b874071 2015-02-08 00:24:03 +0000)`

**Comment by kvark** [comment]
So it's a windows-specific thing? Maybe something to do with the OpenGL context version you are getting.

**Comment by toqueteos** [comment]
Linux / Mac users confirming this would help.

**Comment by kvark** [comment]
Assigned myself on it, but will only be able to look at it later tonight, so please go ahead and investigate if you can.

**Comment by bvssvni** [comment]
Tested on OSX. Same glitch here.

**Comment by kvark** [comment]
Actually, the graphics code seems to be correct. It might not be the rendering part that fails but rather the voxel traversing part.

**Comment by risyasin** [comment]
Same bug/glitch here too. 
All fresh install on osx 10.10.2  
rustc 1.0.0-nightly (00df3251f 2015-02-08 23:24:33 +0000)
MD5 (1.8.1.zip) = 5c9aaf31199f763ef9085cc9b6902b1d

**Comment by risyasin** [comment]
Not sure it's a problem but while compiling hematite i got these warnings. 

![screen shot 2015-02-10 at 02 01 49](https://cloud.githubusercontent.com/assets/283117/6118694/d7c8c314-b0c8-11e4-8201-3d4094f3632d.png)

**Comment by kvark** [comment]
@risyasin yes the first warning is worrisome, but it's not related to the bug.

I verified that it's a logic issue in chunk storage or sorting. The title shows number of blocks total/rendered/sorted, and these stay at 0 when the app is fully loaded. Hence, you are not sending any draw calls.

**Comment by kvark** [comment]
I added another number to the title string (locally) to output the number of chunks pending (i.e. whose buffer is None). This shows all 1082 chunks to be pending after it "loaded". Something seems to be clearing the buffer fields of chunks, but I don't know what. When a chunk is just loaded, it gets rendered properly, but only for a single frame.

**Comment by kvark** [comment]
@huonw advised bissecting Rust to find out if LLVM upgrade caused it:
> multirust may help juggle the installations
> in bash `for n in {01..31}; do multirust update nightly-2015-01-$n; done; for n in {01..10}; do multirust update nightly-2015-02-$n; done`
> will take a while, though
> (maybe s/update/default/ will work better)
> and then just `multirust default nightly 2015-...` will switch without downloading or anything

Yurume:
> (`for d in 2015-{01-{01..31},02-{01..10}}; do multirust update nightly-$d; done` works as well)

It is estimated to take about 24G of the space, which I don't have at the moment:
> 24GB
> I imagine you could also download lazily
> i.e. skip the for loops and just use `multirust default nightly 2015-...` which will download on demand
> (it will cache it, if you ever need to go back)

Any volunteers? :)

**Comment by mattico** [comment]
FWIW, on windows all I get is an empty screen.
![image](https://cloud.githubusercontent.com/assets/853158/6142410/ab1299fe-b17b-11e4-8a26-487926370d7b.png)

**Comment by toqueteos** [comment]
Woah... things changed a bit with latest nightlies guys.

Best way to explain is video: https://www.youtube.com/watch?v=FoQOPwbjmkw

I limitted FPS to 60 by setting https://github.com/PistonDevelopers/hematite/blob/master/src/main.rs#L188 to `60` instead of `10_000`.

As you can see something is slowing down chunk loading.

**Comment by kvark** [comment]
This is getting weirder and weirder. We need to strip down hematite and narrow it to a single function or something...

**Comment by toqueteos** [comment]
#195 gets us working with latest nightlies. Slow chunk loading is gone but chunks are still rendered just once.

**Comment by pharno** [comment]
I also get this glitch (original one, not blank screen) on OSX 10.9, with cargo 0.0.1-pre-nightly (3f74d7e 2015-02-14) (built 2015-02-14). 

My guess is that there is some matrix getting pushed, but not popped again, but im just guessing here.

**Comment by eddyb** [comment]
@pharno There is no Matrix.

**Comment by pharno** [comment]
@eddyb is that a matrix joke or is there legitimately no (opengl) matrix in there?

**Comment by eddyb** [comment]
Hematite never used immediate mode, so no, there's no matrix stack. And I was being cheesy, too.

**Comment by pharno** [comment]
first frame looks normal. after that it kind of "explodes". Set the max fps to 1 and you'll see what I mean.

**Comment by kvark** [comment]
Caused and blocked by https://github.com/rust-lang/rust/issues/22536

**Comment by kvark** [comment]
As a workaround one could try using `b.copy().get()` here:
https://github.com/PistonDevelopers/hematite/blob/master/src/chunk.rs#L113

That would require `#[derive(Copy, Clone)]` on `struct  Buffer`

**Comment by toqueteos** [comment]
@kvark Doesn't work :cry:, `Buffer` contains a `RefBatch` which isn't `Clone`.

**Comment by kvark** [comment]
Verified fixed in latest. Thanks @pnkfelix!

**Comment by bvssvni** [comment]
The end of an epic bug hunt!

**Comment by toqueteos** [comment]
Is this real? Thanks @pnkfelix!
