### ISSUE TITLE
Build fail: trait Copy not implemented

### ISSUE THREAD

**Issue by Yamakaky** [PistonDevelopers/hematite#190]
Hi
I have a build fail with this message:
```rust
src/shader.rs:101:10: 101:14 error: the trait `Copy` may not be implemented for this type; field `batch` does not implement `Copy` [E0204]
src/shader.rs:101 #[derive(Copy)]
                           ^~~~
note: in expansion of #[derive]
src/shader.rs:101:1: 101:16 note: expansion site
```

**Comment by bvssvni** [comment]
Try `cargo update`

**Comment by Yamakaky** [comment]
Now I have a 'Maybe a missing `extern crate std`' in gl_generator ^^

**Comment by bvssvni** [comment]
:laughing:

**Comment by Yamakaky** [comment]
2 secs, I update rust.

**Comment by Yamakaky** [comment]
That was it, it builds now. But
`thread '<main>' panicked at 'Usage: ./hematite <path/to/world>', /home/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libcore/option.rs:330`

**Comment by toqueteos** [comment]
@Yamakaky `cargo run --release "path/to/world"`

**Comment by Yamakaky** [comment]
Ok, thanks. Maybe you should improve this error message ?

**Comment by toqueteos** [comment]
The error is already saying the same thing I said, the only change possible would be not panicking, calling something like `os::exit` (not sure if it exists).
