### ISSUE TITLE
Compile issues on Windows

### ISSUE THREAD

**Issue by Svengali** [PistonDevelopers/hematite#196]
So, with the help of the excellent Reddit sub, I _almost_ got everything compiled.  It looks like things are failing on:

pub struct BlockStates {
    models: Vec<ModelAndBehavior>,
    texture: Texture
}

Texture needs a type argument.  Ive tried all sorts of things.  gfx::GLDevice, gfx::Device, etc.  

Unfortunately, this is my first Rust project, so Im at a loss.  I dont know how to find the info that would let me fix this.

**Comment by toqueteos** [comment]
It's github.com/gfx-rs/gfx-rs, Texture changed and it's missing a generic param.

Send PR or wait until I get home and fix build.

**Comment by toqueteos** [comment]
Ok, I talked with @kvark on IRC (thanks for explanations mate!) and as he suggested we should not fix this, yet. gfx-rs is ongoing major changes and with Rust still on nightlies we better way a bit.

Just in case you want to fix it, adding `gfx::GlResources` on most places complaining about a missing generic param should get you going.

**Comment by kvark** [comment]
@toqueteos I didn't suggest you to not fix it, no! I said you could either put `gfx::GlResources` or make all the thing generic with `<R: Resources>` parameter. The latter is the "right way" to fix it, but it should better wait till https://github.com/gfx-rs/gfx-rs/pull/598 is done.

**Comment by toqueteos** [comment]
Right, let me fix  that.

**Comment by Svengali** [comment]
I added GLResources almost everywhere (COW strings changed too).  

But, I get this for the block_state.rs Texture error:

src\minecraft\block_state.rs:27:1: 30:2 error: the trait `gfx_device_gl::Device` is not implemented for the type `gfx_device_gl::gl_device::GlResources` [E0277]
src\minecraft\block_state.rs:27 pub struct BlockStates {
src\minecraft\block_state.rs:28     models: Vec<ModelAndBehavior>,
src\minecraft\block_state.rs:29     texture: Texture<gfx::GlResources>
src\minecraft\block_state.rs:30 }

**Comment by kvark** [comment]
The `Texture` comes from `gfx_texture::Texture`, which is parametrised by `gfx::Device`.
@Svengali use `texture: Texture<gfx::GlDevice>` instead

**Comment by Svengali** [comment]
Yeah, tried that and just gfx::Device.  For the first one I got:

src\shader.rs:94:35: 94:42 error: mismatched types:
 expected `gfx_device_gl::Handle<u32, gfx_device_gl::tex::SamplerInfo>`,
    found `gfx_device_gl::Handle<<<D as gfx_device_gl::Device>::Resources as gfx_device_gl::Resources>::Sampler, gfx_device_gl::tex::SamplerInfo>`
(expected u32,
    found associated type) [E0308]
src\shader.rs:94             s_texture: (tex, Some(sampler))
                                                   ^~~~~~~
src\shader.rs:109:19: 109:23 error: mismatched types:
 expected `gfx_device_gl::Handle<u32, gfx_device_gl::shade::ProgramInfo>`,
    found `gfx_device_gl::Handle<<<D as gfx_device_gl::Device>::Resources as gfx_device_gl::Resources>::Program, gfx_device_gl::shade::ProgramInfo>`
(expected u32,
    found associated type) [E0308]
src\shader.rs:109             prog: prog,

**Comment by kvark** [comment]
@Svengali that's because `Renderer` (in shaders.rs) is generic over `gfx::Device`. It's a good thing, you just can't combine structures that are generic over something with structures that are specialized. It's not a gfx-rs specific thing, it's how generics work in general.

So, back to the problem. You should either make everything gfx-related to be generic, or to be specialized for GL only. I recommend the former.

**Comment by kvark** [comment]
Our device abstractions work as follows:
```rust
trait Device {
    type Resources;
    ...
}
trait Resources {
    type Buffer;
    type Texture;
    ...
}

impl Device for GlDevice {}
impl Resources for GlResources {}
```

Most of the stuff depends on `Resources`, though some stuff needs `Device` (like `gfx_texture::Texture`), from which you can access `Resources` as an associated type.

**Comment by Svengali** [comment]
Thanks for all the help.  Ive tried all variations, but still not quite doing it.  

Ill keep plugging away, but Im also just sorta waiting for the official fix.

**Comment by kvark** [comment]
@Svengali thank you for trying! And sorry for all the trouble...
I'll fix it tonight if you don't manage to finish it.

**Comment by Svengali** [comment]
I applied @kvark 's changes and it looks like everything loaded.  

Its just a default color background with nothing being rendered at the moment.  But its progress.
