### ISSUE TITLE
Make setup a little easier.

### ISSUE THREAD

**Issue by mattico** [PistonDevelopers/hematite#209]
I'm creating this issue to organize the discussion that started in #177 about making the setup process for hematite a little easier. In particular, [this Gist](https://gist.github.com/toqueteos/e2e2921d4f9e639b0eec) by @toqueteos is of interest. Goals:
* Reduce required arguments as much as possible
* Reduce set-up steps as much as possible
* Simplify world file handling

In order to accomplish this, I propose the following changes:
1. Assume that the minecraft folder is in one of the default locations, unless overridden by a flag.
2. Use the newest supported jar from the minecraft folder, unless overridden by a flag.
3. Automatically extract the jar to `assets/` or just read from it in memory?
4. Don't require a fully qualified path for world folders, assume it's in the minecraft folder. E.g: `hematite world` is equivalent to `hematite ~/.minecraft/saves/world`

Pros:
* Small, localized changes
* Makes hematite easier to use

Cons:
* Zip library dependency
* Flags

**Comment by toqueteos** [comment]
Hmm... flags package. I can finally tinker with docopt!

**Comment by toqueteos** [comment]
gist working at #210, currently not building because of gfx-rs.

**Comment by toqueteos** [comment]
@bvssvni Do we consider this as fixed now that my slowest contrib ever is finally done? #210

**Comment by bvssvni** [comment]
Closed by https://github.com/PistonDevelopers/hematite/pull/210
