### ISSUE TITLE
Upgrade for modern gfx-rs, using Stream/Canvas

### ISSUE THREAD

**Issue by kvark** [PistonDevelopers/hematite#214]
Also, kill SDL2 usage in favor of Glutin and `gfx_window_glutin`, since we are at it.

cc @eddyb

**Comment by mattico** [comment]
I can take this one if you don't mind. I'll see how much glutin I can handle, but I see that there are some changes going on in gfx-rs right now wrt Stream/Canvas, so I'll wait on that.

**Comment by kvark** [comment]
@mattico this is very brave of you! Breaking changes in gfx-rs are currently done inside the v0.5 branch, see the full list in https://github.com/gfx-rs/gfx-rs/issues/737

You can still do the upgrade. The changes needed after gfx-v0.5 will not be major.
