### ISSUE TITLE
Update the Cargo Dependencies Diagram

### ISSUE THREAD

**Issue by mattico** [PistonDevelopers/hematite#220]
Low priority, but I want to remember to update this as it's not currently correct.  I'm having trouble building [cargo-dot](https://github.com/maxsnew/cargo-dot), which might be something to do with my machine as the error is quite strange. I'll file an issue once I'm sure that it's just due to nightly churn. If anyone has a binary sitting around it would be easiest to just use that.

**Comment by fenhl** [comment]
As an alternative to cargo-dot, this could be done with [cargo-lock-to-dot](https://github.com/brson/cargo-lock-to-dot) which does not require compiling a cargo plugin.
